version: '3.9'

services: 
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    networks:
      - mongo-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: employees_info
    ports:
      - 27017:27017

  mongodb-seed:
    image: mongo
    container_name: mongodb-seed
    networks:
      - mongo-net
    depends_on:
      - mongodb
    volumes:
      - /test_task/mongodb-init:/mongodb-init
    links:
      - mongodb
    command:
      mongoimport --host mongodb --db employees_info --collection employees --authenticationDatabase admin --username $MONGODB_USERNAME --password $MONGODB_PASSWORD --drop --jsonArray --file /mongodb-init/employees.json   
      
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongodb
    networks:
      - mongo-net
    ports:
      - 8093:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_PASSWORD
      - ME_CONFIG_MONGODB_AUTH_DATABASE=$MONGODB_USERNAME
      - ME_CONFIG_MONGODB_AUTH_USERNAME=$MONGODB_USERNAME
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=$MONGODB_PASSWORD
      - ME_CONFIG_BASICAUTH_USERNAME=$MONGODB_PASSWORD
      - ME_CONFIG_BASICAUTH_PASSWORD=$MONGODB_PASSWORD

  task:
    container_name: task
    build: .
    ports:
      - 8000:8000
    volumes:
      - /test_task/configs:/home/taskuser/configs
    depends_on:
      - mongodb
    networks:
      - mongo-net


networks:
  mongo-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.30.0/24